-- Seed: the thirteen bench lots off pallets 0442 and 0447.
-- Prices and bid counts from the demo were fiction and are NOT carried over:
-- every lot opens at a dollar with an empty bid table, exactly as the site says.

insert into lots (lot_no, category, title, alt_text, image_path, grade, pallet,
                  found, fixed, still, retail_cents, buy_now_cents,
                  opening_cents, status, opens_at, ends_at, original_ends_at)
select v.lot_no, v.category, v.title, v.alt_text, v.image_path, v.grade::lot_grade, v.pallet,
       v.found, v.fixed, v.still, v.retail_cents, v.buy_now_cents,
       100, 'open', now(), now() + (v.ends_in_s || ' seconds')::interval,
                            now() + (v.ends_in_s || ' seconds')::interval
from (values
  (118, 'Sectional', 'Ariana Double Chaise Sectional, Green Velvet', 'Green velvet double chaise sectional in a styled living room.', 'img/lot-sectional.jpg', 'b', '0442', 'Right chaise seam split about nine inches. Carton crushed on one end in transit.', 'Seam restitched in matching thread, frame checked square, all legs re-torqued.', 'A faint crease in the velvet along the repair. You see it in raking light, not head on.', 249900, null, 8940),
  (119, 'Recliner', 'Kanlow Rocker Recliner, Nutmeg', 'Nutmeg upholstered rocker recliner, three-quarter view.', 'img/lot-recliner.jpg', 'c', '0442', 'Reclining mechanism jammed shut and the release handle snapped off in the carton.', 'New handle assembly and release cable, then cycled forty times on the bench.', 'Scuff on the outside left arm, about the size of a quarter.', 72900, null, 2615),
  (121, 'Dresser and mirror', 'Cornina 6-Drawer Dresser with Mirror', 'Six-drawer dresser with a rectangular mirror, front view.', 'img/lot-dresser.jpg', 'b', '0442', 'Arrived with no drawer pulls and no mirror mounting hardware. Nothing broken, just naked.', 'Full pull set and mirror brackets sourced and fitted, drawers aligned.', 'Two of the eight pulls are a close match rather than an exact one.', 114900, null, 12480),
  (122, 'Dining chairs, pair', 'Milena Dining Chairs, Ivory, Set of 2', 'Pair of ivory upholstered dining chairs.', 'img/lot-chairs.jpg', 'a', '0447', 'Customer return. Box opened, chairs never assembled.', 'Assembled, inspected, hardware confirmed complete.', 'Nothing. This one only lost its box.', 32900, null, 720),
  (124, 'Area rug, 5 x 7', 'Shaggy Area Rug, Brown and Beige', 'Brown and beige shag area rug photographed flat.', 'img/lot-rug.jpg', 'b', '0447', 'Returned with pet hair through the pile and one corner folded in storage.', 'Commercially cleaned, then blocked flat for six days.', 'Slight ripple at one corner. It relaxes under a coffee table.', 21900, null, 26400),
  (125, 'Table lamp', 'Linus Table Lamp, Brushed Brass', 'Brushed brass table lamp base with a drum shade.', 'img/lot-lamp.jpg', 'c', '0447', 'Cord cut off at the plug. No harp and no shade in the carton.', 'Rewired with a new UL cord and plug, new harp fitted, socket tested.', 'Sold without a shade. The one in the photo is not included.', 12900, null, 1140),
  (127, 'Media console, 65 in.', 'Carlina TV Stand, Ivory', 'Ivory media console with open shelving, front view.', 'img/lot-tvstand.jpg', 'c', '0442', 'Front left corner chipped through the finish down to the substrate.', 'Filled, color matched by hand and sealed.', 'The repair reads from about three feet. Farther than that it disappears.', 57900, null, 40200),
  (128, 'Ottoman', 'Ariana Rectangle Ottoman, Ivory Velvet', 'Low ivory velvet rectangular ottoman.', 'img/lot-ottoman.jpg', 'a', '0447', 'Floor sample. Light dust, no damage.', 'Steam cleaned and legs re-torqued.', 'Nothing worth printing.', 34900, 14500, 90600),
  (130, 'Dining bench', 'Lettner Dining Bench, Gray Brown', 'Gray brown wooden dining bench with an upholstered seat.', 'img/lot-bench.jpg', 'b', '0442', 'One leg loose. The screw hole under the seat was stripped out.', 'Hole doweled, re-drilled, glued and clamped overnight.', 'Repair is under the seat. Sound, and you will not see it.', 38900, null, 5400),
  (131, 'Headboard, queen', 'Adinton Panel Headboard, Queen', 'Brown wood-tone queen panel headboard.', 'img/lot-headboard.jpg', 'c', '0447', 'Headboard only. No side rails, no bolt pack.', 'Universal bolt pack included and pre-drilled to fit a standard queen frame.', 'Still no side rails. Bring a frame or plan on one.', 44900, 6000, 172800),
  (133, 'Mattress, king', 'Comfort Plus Euro Top Mattress, King', 'King euro top mattress made up on a gray upholstered bed.', 'img/lot-mattress.jpg', 'a', '0447', 'Carton torn open at a corner in freight. Inner bag never breached.', 'Nothing to fix. Bag is sealed and it has never been slept on.', 'The box is ugly. The mattress is not.', 89900, 34000, 61200),
  (134, 'Counter set, 5 pc', 'Hazelteen Counter Table with Four Stools', 'Medium brown counter height dining table with four matching stools.', 'img/lot-barset.jpg', 'b', '0442', 'One stool came through with a cracked weld at the footrest.', 'Weld ground out, re-run, and repainted to match the set.', 'The repainted section sits about a half shade darker than the others.', 89900, null, 33000),
  (135, 'Wall mirror', 'Modest Round Wall Mirror, Gold', 'Round wall mirror with a thin gold frame.', 'img/lot-mirror.jpg', 'b', '0442', 'Frame separated at one corner joint. Glass untouched.', 'Re-glued, clamped, and hanging hardware added.', 'Hairline gap remains at the top right corner of the frame.', 19900, null, 3300)
) as v (lot_no, category, title, alt_text, image_path, grade, pallet,
        found, fixed, still, retail_cents, buy_now_cents, ends_in_s);
